config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :accounts, except: [:new]
  get "/signup", to: "accounts#new"

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

  # resources :tokens, only: [:index, :create, :destroy]

  namespace :api, {format: "json"} do
    namespace :v1 do
      resources :images, only: [:show, :create, :update, :destroy]
      resources :posts, except: [:new]
      resources :locations, only: [:index, :create]
      get "/accounts/available", to: "accounts#available?"
      post "/posts/locations", to: "posts#add_location"
      get "/count", to: "posts#count"
      get "/dump", to: "posts#dump"
    end
  end

  root "accounts#new"
end

app/models/account.rb
class Account < ApplicationRecord
  validates :name, :password, :birthday, presence: true
  validates :name, uniqueness: true
  validates :name, length: {in: 2..20, message: "は2〜20文字にしてください"}
  validates :password, presence: true, confirmation: true
  validate :encrypt_password
  has_many :posts
  has_many :tokens, dependent: :destroy
  has_many :locations, dependent: :destroy

  def encrypt_password
    self.password = BCrypt::Password.create(self.password)
  end

  class << self
    def authenticate(name, password)
      acc = Account.find_by(name: name)
      acc if acc && BCrypt::Password.new(acc.password) == password
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :check_session, only: [:show]

  def show
    @token = Token.find_by(account: @account)
  end

  def new
    if session[:uid]
      @token = Account.find(session[:uid]).tokens.first.token
      render template: "accounts/create"
    end
    @new_account = @new_account || Account.new
  end

  def create
    bd_keys = %i(birthday(1i) birthday(2i) birthday(3i))
    new_params = params.require(:account).permit([:name, :password, :password_confirmation, :sex] + bd_keys)
    bd_array = [new_params[bd_keys[0]], new_params[bd_keys[1]], new_params[bd_keys[2]]].map(&:to_i)
    birthday = Date.new(bd_array[0], bd_array[1], bd_array[2])

    @new_account = Account.new(
      name: new_params[:name],
      password: new_params[:password],
      birthday: birthday,
      sex: new_params[:sex],
    )

    @new_token = Token.new(account: @new_account, token: SecureRandom::base58) #トークンを1つ作る

    if @new_account.save && @new_token.save
      flash[:notice] = "アカウントが登録されました"
      session[:uid] = @new_account.id
      @token = @new_account.tokens.first.token
    else
      flash[:form_errors] = @new_account.errors.full_messages
      redirect_to action: "new"
    end
  end

  private

  def check_session
    @account = Account.find_by(id: session[:uid])
    if !@account || params[:id] != session[:uid].to_s
      raise ArgumentError.new
      flash[:error] = "ログインされていないか、または不正な画面遷移が起こりました。再度ログインしてください。"
      redirect_to :root
    end
  end
end

app/controllers/api/v1/accounts_controller.rb
class Api::V1::AccountsController < ApiController
  def available?
    token = Token.find_by(token: params[:token])
    if token && token.account
      render json: {status: 200, result: true}
    else
      render json: {status: 200, result: false}
    end
  end
end

app/views/accounts/create.html.erb
<script type = "text/javascript" >
  window.addEventListener("load", function (e) {
    location.replace("tmokku://login/redirect?token=" + document.getElementById("token").value);
  }, false); 
</script>
<h2>Redirecting...</h2>
<form action="">
  <input type="hidden" id="token" value="<%= @token %>">
</form>

app/views/accounts/new.html.erb
<% #= javascript_include_tag "new_account" %>
<% stylesheet_link_tag "signup" %>
<% @title = "新規登録" %>

<div class="container">
<%= form_for @new_account, url: accounts_path do |f| %>

  <% if flash[:form_errors] %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">
        <%= t '.error_count', count: flash[:form_errors].length %>
      </h4>

      <ul>
        <% flash[:form_errors].each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="back">
  <table style="margin: auto">
    <tr>
      <td><%= t 'activerecord.attributes.account.name' %></td>
      <td>
        <%= f.text_field :name, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t 'activerecord.attributes.account.password' %>
      </td>
      <td>
        <%= f.password_field :password, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t 'activerecord.attributes.account.password' %>の確認
      </td>
      <td>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%= t 'activerecord.attributes.account.birthday' %></td>
      <div class="form-group">
      <td>
      <% today = Date.today%>
      <%= f.date_select :birthday, {start_year: today.year - 120, end_year: today.year, use_month_numbers: true, date_separator: "-"}, {class: "js-date-selector"} %>
      </td>
      </div>
    </tr>
    <tr>
    <tr>
      <td><%= t 'activerecord.attributes.account.sex' %></td>
      <td>
        <%= f.select :sex, [["男性", "m"], ["女性", "f"]], class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= f.submit t'.register', class: "btn btn-primary" %>
        または<%= link_to "ログイン", :signin %>
      </td>
    </tr>
  </table>
  </div>
</div>

<% end %>

app/views/accounts/show.html.erb
<% @title = "アカウント詳細" %>

<div class="container">
  <table class="table">
    <tbody>

      <tr>
        <th scope="row">
          名前
        </th>
        <td>
          <%= @account.name %>
        </td>
      </tr>

      <tr>
        <th scope="row">
          アクセスキー
        </th>
        <td>
          <%= @token.token %>
        </td>
      </tr>

    </tbody>
  </table>
</div>